spring:
  profiles:
    active: test
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    open-in-view: false