INSERT INTO tb_category(name) VALUES ('Palmeiras');
INSERT INTO tb_category(name) VALUES ('Internacional');
INSERT INTO tb_category(name) VALUES ('Fluminense');
INSERT INTO tb_category(name) VALUES ('Corinthians');
INSERT INTO tb_category(name) VALUES ('Flamengo');
INSERT INTO tb_category(name) VALUES ('Athletico Paranaense');
INSERT INTO tb_category(name) VALUES ('Atlético Mineiro');
INSERT INTO tb_category(name) VALUES ('Fortaleza');
INSERT INTO tb_category(name) VALUES ('São Paulo');
INSERT INTO tb_category(name) VALUES ('América Mineiro');
INSERT INTO tb_category(name) VALUES ('Botafogo');
INSERT INTO tb_category(name) VALUES ('Santos');
INSERT INTO tb_category(name) VALUES ('Goiás');
INSERT INTO tb_category(name) VALUES ('Red Bull Bragantino');
INSERT INTO tb_category(name) VALUES ('Coritiba');
INSERT INTO tb_category(name) VALUES ('Cuiabá');
INSERT INTO tb_category(name) VALUES ('Ceará');
INSERT INTO tb_category(name) VALUES ('Atlético Goianiense');
INSERT INTO tb_category(name) VALUES ('Avaí');
INSERT INTO tb_category(name) VALUES ('Juventude');
INSERT INTO tb_category(name) VALUES ('Cruzeiro');
INSERT INTO tb_category(name) VALUES ('Grêmio');
INSERT INTO tb_category(name) VALUES ('Bahia');
INSERT INTO tb_category(name) VALUES ('Vasco da Gama');
INSERT INTO tb_category(name) VALUES ('Sampaio Corrêa');
INSERT INTO tb_category(name) VALUES ('Ituano');
INSERT INTO tb_category(name) VALUES ('Sport');
INSERT INTO tb_category(name) VALUES ('Criciúma');
INSERT INTO tb_category(name) VALUES ('Londrina');
INSERT INTO tb_category(name) VALUES ('Guarani');
INSERT INTO tb_category(name) VALUES ('CRB');
INSERT INTO tb_category(name) VALUES ('Ponte Preta');
INSERT INTO tb_category(name) VALUES ('Vila Nova');
INSERT INTO tb_category(name) VALUES ('Chapecoense');
INSERT INTO tb_category(name) VALUES ('Tombense');
INSERT INTO tb_category(name) VALUES ('Novorizontino');
INSERT INTO tb_category(name) VALUES ('CSA');
INSERT INTO tb_category(name) VALUES ('Brusque');
INSERT INTO tb_category(name) VALUES ('Operário-PR');
INSERT INTO tb_category(name) VALUES ('Náutico');